# -*- coding: utf-8 -*-
"""Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfVQTX9sYEtt0ry3gGYQVTez6Lj4Wqjt
"""

import random
import time
import os
import string

# ---------------------------
# 工具：清除畫面（Windows 用 cls）
# ---------------------------
def clear_screen():
    os.system("cls")

# ---------------------------
# 工具：按 Enter 返回
# ---------------------------
def wait_return():
    input("\n按 Enter 返回主選單...")

# ---------------------------
# 檔案：讀取排行榜
# ---------------------------
def load_scores(filename):
    if not os.path.exists(filename):
        return []
    with open(filename, "r", encoding="utf-8") as f:
        scores = f.read().strip().split("\n")
        return [float(s) for s in scores if s.strip()]

# ---------------------------
# 檔案：存入排行榜
# ---------------------------
def save_scores(filename, scores):
    with open(filename, "w", encoding="utf-8") as f:
        for s in scores:
            f.write(f"{s}\n")

# ---------------------------
# 排行榜資料檔名與載入
# ---------------------------
blackjack_scores_file = "blackjack_scores.txt"
blackjack_scores = load_scores(blackjack_scores_file)

ultimate_scores_file = "ultimate_scores.txt"
ultimate_scores = load_scores(ultimate_scores_file)

code_scores_file = "code_scores.txt"
code_scores = load_scores(code_scores_file)

memory_scores_file = "memory_scores.txt"
memory_scores = load_scores(memory_scores_file)

# ---------------------------
# 漂亮排行榜輸出（可指定單位與排序方向）
# unit: '%' / '秒' / '次'
# ascending: True = 小到大 (例如次數、時間)，False = 大到小 (例如百分比)
# ---------------------------
def show_leaderboard(title, score_list, unit='%', ascending=False):
    clear_screen()
    print(f"──────────── 🏆 排行榜：{title} 🏆 ────────────")
    if not score_list:
        print("（目前沒有紀錄）")
    else:
        sorted_scores = sorted(score_list, reverse=not ascending)
        for i, score in enumerate(sorted_scores[:10], start=1):
            if unit == '%':
                print(f" {i:>2}. {score:>6.2f}%")
            elif unit == '秒':
                print(f" {i:>2}. {score:>6.2f} 秒")
            else:  # unit == '次' 或其他
                # 把分數顯示為整數次數
                print(f" {i:>2}. {int(score):>3d} 次")
    print("───────────────────────────────────────────────")
    wait_return()

# =====================================================
#                21 點 BLACKJACK
# =====================================================
suits = ["♠", "♥", "♦", "♣"]
ranks = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]

def rank_value(rank):
    if rank in ["J","Q","K"]:
        return 10
    if rank=="A":
        return 11
    return int(rank)

def create_deck():
    deck = [(s,r) for s in suits for r in ranks]
    random.shuffle(deck)
    return deck

def calculate_score(cards):
    total = 0
    ace_cnt = 0
    for (s,r) in cards:
        v = rank_value(r)
        total += v
        if r=="A":
            ace_cnt += 1
    while total>21 and ace_cnt>0:
        total -= 10
        ace_cnt -= 1
    return total

def deal_animation(name="你"):
    print(f"{name}抽牌中：", end="", flush=True)
    for _ in range(3):
        print("▮", end="", flush=True)
        time.sleep(0.25)
    print(" → ", end="", flush=True)

def blackjack_rules():
    clear_screen()
    print("────────── 📖 21 點 Blackjack 規則 ──────────")
    print("""
1. 玩家與莊家各發兩張牌。
2. 玩家可選擇繼續抽牌或停牌。
3. 點數計算：
   A = 1 或 11
   J/Q/K = 10
   其他牌 = 面值
4. 超過 21 點爆牌。
5. 莊家必須抽到 ≥17 才能停牌。
6. 連續玩滿 5 局才會把勝率記入排行榜。
    """)
    print("──────────────────────────────────────────────")
    wait_return()

def blackjack_game():
    global blackjack_scores
    clear_screen()
    session_games=0
    total_games=0
    wins=0

    while True:
        clear_screen()
        deck=create_deck()
        total_games+=1
        session_games+=1

        print(f"=== Blackjack 第 {session_games} 局 ===\n")

        player=[deck.pop(),deck.pop()]
        dealer=[deck.pop(),deck.pop()]

        print("你的手牌：", [s+r for (s,r) in player])
        print("莊家明牌：", dealer[0][0]+dealer[0][1])

        while True:
            choice = input("\n要抽牌嗎？(y/n)：").lower()
            if choice=="y":
                deal_animation("你")
                card=deck.pop()
                print(card[0]+card[1])
                player.append(card)
                if calculate_score(player)>21:
                    print("你爆牌了！")
                    break
            elif choice=="n":
                break

        p = calculate_score(player)
        if p<=21:
            print("\n莊家手牌：", [s+r for (s,r) in dealer])
            d = calculate_score(dealer)
            while d<17:
                deal_animation("莊家")
                card=deck.pop()
                print(card[0]+card[1])
                dealer.append(card)
                d=calculate_score(dealer)
        else:
            d = calculate_score(dealer)

        print("\n最終結果：")
        print("玩家：",p)
        print("莊家：",d)

        if p>21:
            print("莊家勝。")
        elif d>21 or p>d:
            print("🎉 你贏了！")
            wins+=1
        elif p==d:
            print("平手！")
        else:
            print("莊家勝。")

        win_rate = wins/total_games*100
        print(f"\n勝率：{win_rate:.2f}%")

        again = input("\n要再玩一局嗎？(y/n)：").lower()
        if again!="y":
            break

    if session_games>=5:
        blackjack_scores.append(win_rate)
        save_scores(blackjack_scores_file, blackjack_scores)
        print("\n已加入排行榜！")
    else:
        print("\n未達五局，未加入排行榜。")
    wait_return()

# =====================================================
# 終極密碼 Ultimate Password
# =====================================================
def ultimate_rules():
    clear_screen()
    print("────────── 📖 終極密碼 Ultimate Password 規則 ──────────")
    print("""
1. 會隨機產生 1～100 的數字。
2. 玩家輪流猜數字。
3. 猜錯會提示更小或更大的區間。
4. 猜中的人「輸」。
5. 玩滿 5 局才會把勝率加入排行榜。
    """)
    print("──────────────────────────────────────────────")
    wait_return()

def ultimate_game():
    global ultimate_scores
    clear_screen()

    games=0
    wins=0

    while True:
        clear_screen()
        games+=1
        print(f"=== 終極密碼 第 {games} 局 ===\n")

        answer = random.randint(1,100)
        low, high = 1,100
        turn = 0 # 0=玩家,1=電腦

        while True:
            print(f"目前範圍：{low} ~ {high}")
            if turn==0:
                guess_input=input("你猜：")
                if not guess_input.isdigit():
                    print("❌ 請輸入有效的整數！")
                    continue
                guess=int(guess_input)
                if guess<=low or guess>=high:
                    print(f"⚠️ 數字不在範圍 {low} ~ {high} 內，請重新輸入")
                    continue
            else:
                guess=random.randint(low,high)
                print(f"電腦猜：{guess}")
                time.sleep(0.6)

            if guess==answer:
                if turn==0:
                    print("你猜中了！你輸了。")
                else:
                    print("電腦猜中！你贏了🎉")
                    wins+=1
                break
            elif guess<answer:
                low=max(low,guess+1)
            else:
                high=min(high,guess-1)

            turn = 1-turn

        win_rate = wins/games*100
        print(f"\n你的勝率：{win_rate:.2f}%")
        again = input("\n要再玩一局嗎？(y/n)：").lower()
        if again!="y":
            break

    if games>=5:
        ultimate_scores.append(win_rate)
        save_scores(ultimate_scores_file, ultimate_scores)
        print("\n已加入排行榜！")
    else:
        print("\n未達五局，未加入排行榜。")
    wait_return()

# =====================================================
# 亂碼挑戰 Code Challenge
# =====================================================
def code_challenge_rules():
    clear_screen()
    print("────────── 📖 亂碼挑戰 Code Challenge 規則 ──────────")
    print("""
1. 每局有五題亂碼。
2. 玩家必須輸入與亂碼完全相同。
3. 輸入錯誤就必須從頭再輸入。
4. 記錄完成 5 題的最快時間。
5. 排行榜紀錄最快時間。
    """)
    print("──────────────────────────────────────────────")
    wait_return()

def code_challenge_game():
    global code_scores
    clear_screen()
    NUM_ROUNDS = 5
    codes = string.ascii_letters + string.digits

    start_time = time.time()
    for i in range(NUM_ROUNDS):
        code = "".join(random.choice(codes) for _ in range(6))
        while True:
            print(f"\n題目 {i+1}/{NUM_ROUNDS}：{code}")
            user_input = input("輸入亂碼：")
            if user_input==code:
                print("✅ 正確！")
                break
            else:
                print("❌ 錯誤，請從頭再輸入")
    end_time = time.time()
    elapsed = end_time - start_time
    print(f"\n🎉 完成五題亂碼挑戰！用時 {elapsed:.2f} 秒")

    code_scores.append(elapsed)
    save_scores(code_scores_file, code_scores)
    print("已加入排行榜！")
    wait_return()

# =====================================================
# 記憶翻牌 Memory Match (4x4, emoji, 翻錯自動蓋回)
# =====================================================
def memory_rules():
    clear_screen()
    print("────────── 📖 記憶翻牌 Memory Match 規則 ──────────")
    print("""
1. 棋盤為 4x4，共 8 對(16 張)牌。
2. 每回合翻兩張，若相同則保持翻開，若不同則自動蓋回。
3. 統計翻牌回合數（每次翻兩張算 1 回合）。
4. 排行榜依翻牌回合數由少到多排序（次數越少越厲害）。
    """)
    print("──────────────────────────────────────────────")
    wait_return()

def memory_game():
    global memory_scores
    clear_screen()
    print("=== 記憶翻牌 Memory Match（4x4，emoji） ===")
    input("按 Enter 開始遊戲...")

    # emoji 候選（選 8 個）
    pool = ["🐶","🐱","🦊","🐼","🐻","🐵","🦁","🐸","🐤","🦄","🐰","🐯"]
    emojis = random.sample(pool, 8)  # 取 8 個不同 emoji
    cards = emojis * 2
    random.shuffle(cards)

    # 將一維列表轉為 4x4
    board = [cards[i*4:(i+1)*4] for i in range(4)]
    revealed = [[False]*4 for _ in range(4)]

    def display_board():
        clear_screen()
        print("   0  1  2  3")
        print("  -------------")
        for r in range(4):
            row = f"{r}| "
            for c in range(4):
                if revealed[r][c]:
                    row += board[r][c] + " "
                else:
                    row += "*  "
            print(row)
        print("  -------------")

    rounds = 0  # 每翻兩張算一回合

    while True:
        display_board()
        # 取得第一張
        pos1 = input("翻第一張（格式 rowcol，例如 02）：").strip()
        if len(pos1) != 2 or (not pos1.isdigit()):
            print("輸入格式錯誤！請輸入兩位數字，例如 02")
            time.sleep(0.8)
            continue
        r1, c1 = int(pos1[0]), int(pos1[1])
        if not (0 <= r1 <4 and 0<= c1 <4):
            print("座標超出範圍！")
            time.sleep(0.8)
            continue
        if revealed[r1][c1]:
            print("這張牌已經翻開了！")
            time.sleep(0.8)
            continue

        revealed[r1][c1] = True
        display_board()

        # 取得第二張
        pos2 = input("翻第二張（格式 rowcol，例如 13）：").strip()
        if len(pos2) != 2 or (not pos2.isdigit()):
            print("輸入格式錯誤！請輸入兩位數字，例如 13")
            revealed[r1][c1] = False
            time.sleep(0.8)
            continue
        r2, c2 = int(pos2[0]), int(pos2[1])
        if not (0 <= r2 <4 and 0<= c2 <4):
            print("座標超出範圍！")
            revealed[r1][c1] = False
            time.sleep(0.8)
            continue
        if revealed[r2][c2]:
            print("這張牌已經翻開了！")
            revealed[r1][c1] = False
            time.sleep(0.8)
            continue
        if r1==r2 and c1==c2:
            print("不能選同一張！")
            revealed[r1][c1] = False
            time.sleep(0.8)
            continue

        revealed[r2][c2] = True
        display_board()

        # 判斷是否配對
        rounds += 1
        if board[r1][c1] == board[r2][c2]:
            print("🎉 配對成功！")
            time.sleep(0.8)
        else:
            print("✖ 配對失敗，將自動蓋回去")
            time.sleep(1.0)
            revealed[r1][c1] = False
            revealed[r2][c2] = False

        # 檢查是否全部配對完成
        all_done = all(revealed[r][c] for r in range(4) for c in range(4))
        if all_done:
            display_board()
            print(f"\n🎉 恭喜完成！總回合數：{rounds} 回合（每回合翻兩張）")
            # 存入排行榜（次數）
            memory_scores.append(rounds)
            save_scores(memory_scores_file, memory_scores)
            print("已加入排行榜！")
            wait_return()
            break

# =====================================================
#               主畫面 GAME HUB
# =====================================================
def display_main_menu():
    clear_screen()
    print("──────────── GAME HUB ────────────")
    print("🎮 1. Blackjack 21 點")
    print("🎯 2. 終極密碼 Ultimate Password")
    print("💻 3. 亂碼挑戰 Code Challenge")
    print("🧠 4. 記憶翻牌 Memory Match")
    print("📖 5. 規則 Rule Book")
    print("🏆 6. 排行榜 Leaderboards")
    print("❌ 0. 離開 Exit")
    print("────────────────────────────────")

def rule_book():
    clear_screen()
    print("────────── 📖 遊戲規則 Rule Book ──────────")
    print("1. 21 點 Blackjack")
    print("2. 終極密碼 Ultimate Password")
    print("3. 亂碼挑戰 Code Challenge")
    print("4. 記憶翻牌 Memory Match")
    print("0. 返回")
    print("────────────────────────────────")
    choice = input("選擇規則編號：")
    if choice=="1":
        blackjack_rules()
    elif choice=="2":
        ultimate_rules()
    elif choice=="3":
        code_challenge_rules()
    elif choice=="4":
        memory_rules()

def leaderboard_menu():
    clear_screen()
    print("────────── 🏆 Leaderboards 排行榜 ──────────")
    print("1. 21 點 Blackjack")
    print("2. 終極密碼 Ultimate Password")
    print("3. 亂碼挑戰 Code Challenge")
    print("4. 記憶翻牌 Memory Match")
    print("0. 返回")
    print("────────────────────────────────")
    choice = input("選擇排行榜編號：")
    if choice=="1":
        show_leaderboard("Blackjack 21 點", blackjack_scores, unit='%', ascending=False)
    elif choice=="2":
        show_leaderboard("終極密碼", ultimate_scores, unit='%', ascending=False)
    elif choice=="3":
        show_leaderboard("亂碼挑戰", code_scores, unit='秒', ascending=True)
    elif choice=="4":
        show_leaderboard("記憶翻牌", memory_scores, unit='次', ascending=True)

def game_hub():
    while True:
        display_main_menu()
        choice=input("請輸入選項：")
        if choice=="1":
            blackjack_game()
        elif choice=="2":
            ultimate_game()
        elif choice=="3":
            code_challenge_game()
        elif choice=="4":
            memory_game()
        elif choice=="5":
            rule_book()
        elif choice=="6":
            leaderboard_menu()
        elif choice=="0":
            clear_screen()
            print("感謝遊玩！再見 🎉")
            break
        else:
            input("輸入錯誤，按 Enter 返回...")

# =====================================================
#                    執行程式
# =====================================================
game_hub()