# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-w1oUh29WIchA-0VL3-tTsmV5IHaj8z
"""

List = input().split()
sum = 0
for i in List:
  if int(i) <60:
    sum += 1
maxvalue = max(List)
minvalue = min(List)

print(maxvalue)
print(minvalue)